Allow PHP 8
Geolid/phpcs pull request #36
Opened 2020-12-14 10:28 UTC by mnapoli

2020-12-14 13:27 UTC, Kleinast commented
It's seem FriendsOfPHP/PHP-CS-Fixer doesn't support php 8 yet (https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4702)
But if it's composer requirement problem you have like here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5326, I can accept if you change only the composer.json in your PR.

2020-12-14 13:27 UTC, Kleinast requested changes

2020-12-14 13:27 UTC, Kleinast commented on .travis.yml
> +  - 8.0
```suggestion
```

2020-12-14 13:57 UTC, mnapoli commented
Make sense, I updated it thanks!

2020-12-15 15:01 UTC, Kleinast approved these changes

2020-12-15 15:03 UTC, merged

2020-12-15 15:22 UTC, mnapoli commented
Thanks!

2020-12-15 16:31 UTC, Kleinast commented
My pleasure, thanks for the contribution.